### ISSUE TITLE
Add support for optional strings in `PacketField`

### ISSUE THREAD

**Issue by wcampbell0x2a** [iwanders/wireshark_dissector_rs#3]
This would transform into 
```
    pub strings: *const libc::c_char, // actually void ptr
```

In c, it would look like the following:
```
static const value_string packettypenames[] = {
    { 1, "Initialise" },
    { 2, "Terminate" },
    { 3, "Data" },
    { 0, NULL }
};

   { &hf_foo_pdu_type,
        { "FOO PDU Type", "foo.type",
        FT_UINT8, BASE_DEC,
        VALS(packettypenames), 0x0,
        NULL, HFILL }
    }
```

**Comment by iwanders** [comment]
Hmm, yeah, I've been thinking about how to do enums like this, this would be neat...

The main roadblock to adding this is that I would want the value_strings to be a vector, and then simply instantiating [them as const](https://github.com/iwanders/wireshark_dissector_rs/blob/master/examples/dummy.rs#L27-L32) won't work anymore. I actually started [going down that route](https://github.com/iwanders/wireshark_dissector_rs/tree/feature-string-enums) and ran into this problem.

So I think the right way to tackle this one, is to act on the [todo](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/dissector.rs#L94) here;
- Remove `PacketField`, it was only something I made to have a safe thing to make a [header_field_info](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan/proto.rs#L98).
- Change [HeaderFieldInfo](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan.rs#L147-L195) into a trait, with only read methods like that struct currently has.
- Have the thin implementation for something that wraps the [pointer](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan.rs#L148-L150). Now that I think of it, the accessors may need to return owned values for strings then.
- The user can make up whatever `PacketField` / `HeaderFieldInfo` he or she wants, which allows for a const definition as we currently have with the `PacketField`, as well as something that is complex and returns vectors of ValueStrings.
- Switch the signatures that use [`PacketField`](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/dissector.rs#L27-L31) to use `Box<dyn HeaderFieldInfo>`.
- When registration happens, the methods on `dyn HeaderFieldInfo` are used to build up the real `header_field_info` which we leak, like we currently do.

Definitely adds some complexity... but I guess this opens the door to supporting anything the `header_field_info` can do? Any thoughts on this approach? On a side note, do you know what Wireshark does when it decodes a value that's not in the provided value string list?

**Comment by wcampbell0x2a** [comment]
> Hmm, yeah, I've been thinking about how to do enums like this, this would be neat...
> 
> The main roadblock to adding this is that I would want the value_strings to be a vector, and then simply instantiating [them as const](https://github.com/iwanders/wireshark_dissector_rs/blob/master/examples/dummy.rs#L27-L32) won't work anymore. I actually started [going down that route](https://github.com/iwanders/wireshark_dissector_rs/tree/feature-string-enums) and ran into this problem.
> 
> So I think the right way to tackle this one, is to act on the [todo](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/dissector.rs#L94) here;
> 
>     * Remove `PacketField`, it was only something I made to have a safe thing to make a [header_field_info](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan/proto.rs#L98).
> 
>     * Change [HeaderFieldInfo](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan.rs#L147-L195) into a trait, with only read methods like that struct currently has.
> 
>     * Have the thin implementation for something that wraps the [pointer](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/epan.rs#L148-L150). Now that I think of it, the accessors may need to return owned values for strings then.

I think this is the best route, especially if that pointer has the same accessor functions that `PacketField` currently provides.

>     * The user can make up whatever `PacketField` / `HeaderFieldInfo` he or she wants, which allows for a const definition as we currently have with the `PacketField`, as well as something that is complex and returns vectors of ValueStrings.
> 
>     * Switch the signatures that use [`PacketField`](https://github.com/iwanders/wireshark_dissector_rs/blob/master/src/dissector.rs#L27-L31) to use `Box<dyn HeaderFieldInfo>`.
> 
>     * When registration happens, the methods on `dyn HeaderFieldInfo` are used to build up the real `header_field_info` which we leak, like we currently do.
> 
> 
> Definitely adds some complexity... but I guess this opens the door to supporting anything the `header_field_info` can do? Any thoughts on this approach? 

I definitely don't know the _perfect_ solution, but this would make it way more extendable yes. I like it.

> On a side note, do you know what Wireshark does when it decodes a value that's not in the provided value string list?

No idea.

**Comment by iwanders** [comment]
@wcampbell0x2a , I took a stab at it today, please see #4. This adds the functionality for showing strings based on the dissected value. Comments welcome.

> do you know what Wireshark does when it decodes a value that's not in the provided value string list?

It displays unknown :+1:
